version: "3" #This denotes that we are using version 3 of Docker Compose
services: #This section defines all the different containers we will create.
    showniq-web_production: #This is the name of our Nextjs application.
        image: "showniq-web_production"
        build: #This specifies the location of our Dockerfile
            context: . #This specifies the location of our Dockerfile
            dockerfile: ./Dockerfile
        ports: #This is used to map the container’s ports to the host machine.
            - "3008:3008"
        restart: always
